{% set name = "lumen" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}-bundle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 575a9ef9444eda55a087c0201345d12ce1743f702538cf3170803a4c57d671e6

build:
  number: 0

outputs:
  - name: {{ name|lower }}
    build:
      entry_points:
        - lumen = lumen.command:main
      skip: True  # [py<310]
      script: python -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
    requirements:
      host:
        - python
        - pip
        - hatchling
        - hatch-vcs
      run:
        - python
        - panel >=1.5.0
        - hvplot
        - holoviews >=1.17.0
        - pandas
        - bokeh
        - intake <2
        - jinja2 >3.0
        - numpy
        - packaging
        - param >=1.9.0
        - sqlglot
        - pydantic-extra-types
        - jsonschema
        - nbformat
      run_constrained:
        - instructor >=1.6.4
        - pydantic >=2.8.0
        - panel-graphic-walker >=0.6.4
        - llama-cpp-python >=0.3.0
    test:
      imports:
        - lumen
        - lumen.ai
        - lumen.auth
        - lumen.command
        - lumen.tests
        - lumen.util
        - lumen.validation
        - lumen.views
      requires:
        - pip
      commands:
        - pip check
        - lumen --help
    about:
      home: https://github.com/holoviz/lumen
      summary: 'Illuminate your data. A monitoring solution built on Panel'
      description: |
        The Lumen project provides a framework for visual analytics, which allows users to
        build data-driven dashboards from a simple yaml specification. The power of
        Lumen comes from the ability to leverage the powerful data intake, data processing
        and data visualization libraries available in the PyData ecosystem.
      license: BSD-3-Clause
      license_file: LICENSE
      license_family: BSD
      doc_url: https://lumen.holoviz.org/
      dev_url: https://github.com/holoviz/lumen
# This recipe builds multiple outputs:
# - lumen: The main package with core functionality
# - lumen-ai: Package with all AI dependencies (except provider-specific ones)
# - lumen-ai-local: Metapackage that adds huggingface_hub for local AI models
# - lumen-ai-openai: Metapackage that adds OpenAI support
# - lumen-ai-mistralai: Metapackage that adds MistralAI support
# - lumen-ai-anthropic: Metapackage that adds Anthropic support
# Until all of the neccesary panel-graphic-walker[kernel] packages are available in defaults,
#  it has been decided to skip the builds for all of Lumen's additional AI outputs.

  - name: {{ name|lower }}-ai
    build:
      skip: True
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - {{ pin_subpackage('lumen', exact=True) }}
        - griffe
        - nbformat
        - duckdb >=1.2.0
        - pyarrow
        - instructor >=1.6.4
        - pydantic >=2.8.0
        - pydantic-extra-types
        - panel-graphic-walker >=0.6.4
        - markitdown
    about:
      home: https://github.com/holoviz/lumen
      summary: 'Lumen with AI capabilities'
      license: BSD-3-Clause
      license_family: BSD

  - name: {{ name|lower }}-ai-local
    build:
      skip: True
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('lumen-ai', exact=True) }}
        - huggingface_hub
    about:
      home: https://github.com/holoviz/lumen
      summary: 'Lumen with huggingface_hub for local AI models'
      license: BSD-3-Clause
      license_family: BSD

  - name: {{ name|lower }}-ai-openai
    build:
      skip: True
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('lumen-ai', exact=True) }}
        - openai
    about:
      home: https://github.com/holoviz/lumen
      summary: 'Lumen with OpenAI support'
      license: BSD-3-Clause
      license_family: BSD

  - name: {{ name|lower }}-ai-mistralai
    build:
      skip: True
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('lumen-ai', exact=True) }}
        - mistralai
    about:
      home: https://github.com/holoviz/lumen
      summary: 'Lumen with MistralAI support'
      license: BSD-3-Clause
      license_family: BSD

  - name: {{ name|lower }}-ai-anthropic
    build:
      skip: True
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('lumen-ai', exact=True) }}
        - anthropic
    about:
      home: https://github.com/holoviz/lumen
      summary: 'Lumen with Anthropic support'
      license: BSD-3-Clause
      license_family: BSD

about:
  home: https://github.com/holoviz/lumen
  summary: 'Illuminate your data. A monitoring solution built on Panel'
  description: |
    Metapackage for lumen and its variants.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://lumen.holoviz.org/
  dev_url: https://github.com/holoviz/lumen

extra:
  recipe-maintainers:
    - Hoxbro
    - philippjfr
