{% set name = "lumen" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 575a9ef9444eda55a087c0201345d12ce1743f702538cf3170803a4c57d671e6

build:
  number: 0
  entry_points:
    - lumen = lumen.command:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=30.3.0
    - hatchling
    - hatch-vcs
  run:
    - python
    - panel >=1.5.0
    - hvplot
    - holoviews >=1.17.0
    - pandas
    - bokeh
    - intake <2
    - jinja2 >3.0
    - numpy
    - packaging
    - param >=1.9.0
    - sqlglot

test:
  imports:
    - lumen
  requires:
    - pip
  commands:
    - pip check
    - lumen --help

about:
  home: https://github.com/holoviz/lumen
  summary: 'Illuminate your data. A monitoring solution built on Panel'
  description: |
    The Lumen project provides a framework for visual analytics, which allows users to
    build data-driven dashboards from a simple yaml specification. The power of
    Lumen comes from the ability to leverage the powerful data intake, data processing
    and data visualization libraries available in the PyData ecosystem.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://lumen.holoviz.org/
  dev_url: https://github.com/holoviz/lumen

extra:
  recipe-maintainers:
    - Hoxbro
    - philippjfr
